# 1. Scenario: Checking for a File and Taking Action
# Question: Write a Playbook to check if a file named "example.txt" exists in the current directory. 
# If it exists, print "File exists." Otherwise, create the file and print "File created."


---
- name: Check for a file and take action
  hosts: localhost
  tasks:
    - name: Check if example.txt exists
      stat:
        path: "./example.txt"
      register: file_status

    - name: Print message if file exists
      debug:
        msg: "File exists."
      when: file_status.stat.exists

    - name: Create file and print message if file does not exist
      command: touch ./example.txt
      when: not file_status.stat.exists

    - name: Print message after file creation
      debug:
        msg: "File created."
      when: not file_status.stat.exists



# Explanation: 
# The playbook first checks if example.txt exists.
# If it does, it simply prints a message. If it doesn't, it creates the file and then prints a confirmation message.

# Note: The last task (printing a message after file creation) is redundant,
# as it will only run if the file didn't exist, which is already covered in the previous task. 
# It can be safely removed without affecting the playbook's functionality.

# By using the stat module and conditional logic, the playbook efficiently handles 
# both scenarios where the file exists and where it doesn't.
